/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_minie_minie_SmartDoor */

#ifndef _Included_cn_minie_minie_SmartDoor
#define _Included_cn_minie_minie_SmartDoor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_minie_minie_SmartDoor_version
  (JNIEnv *, jobject);

/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_minie_minie_SmartDoor_init
  (JNIEnv *, jobject);

/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    getCards
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_minie_minie_SmartDoor_getCards
  (JNIEnv *, jobject);

/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    setCards
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_minie_minie_SmartDoor_setCards
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    addCard
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_minie_minie_SmartDoor_addCard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    removeCard
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_minie_minie_SmartDoor_removeCard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    tests
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_minie_minie_SmartDoor_tests
  (JNIEnv *, jobject);

/*
 * Class:     cn_minie_minie_SmartDoor
 * Method:    Run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_minie_minie_SmartDoor_Run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
